## Basic Configuration
baseurl = "https://vincentz.netlify.com/"
languageCode = "en"

title = "Vincent Zhu"
theme = "hyde-hyde"

## Hugo Built-in Features
# disqusShortname = "your-disqus-shortname"
# googleAnalytics = "your-google-analytics-id"
# enableRobotsTXT = true

# summarylength = 30

#paginate = 5

## Site Settings
[params]
    author = "Vincent Zhu"
    title = "Vincent Zhu"
    # description = "..."
    authorimage = "/img/Face.jpg"
    dateformat = "Jan 2, 2006"

    # sidebar, copyright & license
    copyright = "Vincent Zhu"
    
    showBuiltWith = true

    # https://highlightjs.org
    highlightjs = true
    highlightjsstyle = "github"
    
    # please choose either GraphComment or Disqus or Utterances
    #GraphCommentId = "..."
    #UtterancesRepo = "..." # https://utteranc.es/
    #UtterancesIssueTerm = "..." # pathname, url, title, og:title
    #UtterancesTheme = "..." # github-light or github-dark

    # Table of contents
    #toc = none, "hugo", or "tocbot"

## Social Accounts
[params.social]
    
    instagram = "vinzhu07"
    linkedin = "vinzhu07"
    email = "vinzhu07@gmail.com"
    
   

## Main Menu
[[menu.main]]
    name = "Posts"
    weight = 300
    identifier = "posts"
    url = "/posts/"
[[menu.main]]
    name = "Experience"
    identifier = "Experience"
    weight = 200
    url = "/experience/"
[[menu.main]]
    name = "About"
    identifier = "about"
    weight = 100
    url = "/about/"
